Imported Debian patch 0.9.6-3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19114,14 +19114,19 @@ echo "$as_me: TARGET=$target " >&6;}
         if test x$ac_cv_c_compiler_gnu = xyes; then
             CXXFLAGS="-g -mcpu=i686 -march=i686 -ffast-math -fomit-frame-pointer"
         fi
+        CXXFLAGS="$CXXFLAGS -O3"
+        ;;
+    m68k-*-*)
+        CXXFLAGS="$CXXFLAGS -O2"
         ;;
     *-*-*)
-    if test x$ac_cv_c_compiler_gnu = xyes; then
-        CXXFLAGS="-g -fomit-frame-pointer"
-    fi
-    ;;
+        if test x$ac_cv_c_compiler_gnu = xyes; then
+            CXXFLAGS="-g -fomit-frame-pointer"
+        fi
+        CXXFLAGS="$CXXFLAGS -O3"
+        ;;
     esac
-    CXXFLAGS="$CXXFLAGS -O3 -DNDEBUG"
+    CXXFLAGS="$CXXFLAGS -DNDEBUG"
 fi
 
 if test x$ac_cv_c_compiler_gnu = xyes; then
@@ -20484,44 +20489,37 @@ echo "${ECHO_T}no" >&6
 fi
 
 pkg_failed=no
-echo "$as_me:$LINENO: checking for GTK_CFLAGS" >&5
-echo $ECHO_N "checking for GTK_CFLAGS... $ECHO_C" >&6
-if test "${pkg_cv_GTK_CFLAGS+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for GTK" >&5
+echo $ECHO_N "checking for GTK... $ECHO_C" >&6
+
+if test -n "$PKG_CONFIG"; then
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\"gtk+-2.0 gdk-pixbuf-2.0\"\"") >&5
+  ($PKG_CONFIG --exists --print-errors ""gtk+-2.0 gdk-pixbuf-2.0"") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTK_CFLAGS=`$PKG_CONFIG --cflags ""gtk+-2.0 gdk-pixbuf-2.0"" 2>/dev/null`
 else
-  if test "x$ac_cv_env_GTK_CFLAGS_set" = "xset"; then
-	pkg_cv_GTK_CFLAGS=$ac_cv_env_GTK_CFLAGS_value
-elif test -n "$PKG_CONFIG"; then
-	if $PKG_CONFIG --exists ""gtk+-2.0 gdk-pixbuf-2.0"" >/dev/null 2>&1; then
-		pkg_cv_GTK_CFLAGS=`$PKG_CONFIG --cflags ""gtk+-2.0 gdk-pixbuf-2.0"" 2>/dev/null`
-	else
-		pkg_failed=yes
-	fi
-else
-	pkg_failed=untried
+  pkg_failed=yes
 fi
-fi
-echo "$as_me:$LINENO: result: $pkg_cv_GTK_CFLAGS" >&5
-echo "${ECHO_T}$pkg_cv_GTK_CFLAGS" >&6
-echo "$as_me:$LINENO: checking for GTK_LIBS" >&5
-echo $ECHO_N "checking for GTK_LIBS... $ECHO_C" >&6
-if test "${pkg_cv_GTK_LIBS+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test "x$ac_cv_env_GTK_LIBS_set" = "xset"; then
-	pkg_cv_GTK_LIBS=$ac_cv_env_GTK_LIBS_value
-elif test -n "$PKG_CONFIG"; then
-	if $PKG_CONFIG --exists ""gtk+-2.0 gdk-pixbuf-2.0"" >/dev/null 2>&1; then
-		pkg_cv_GTK_LIBS=`$PKG_CONFIG --libs ""gtk+-2.0 gdk-pixbuf-2.0"" 2>/dev/null`
-	else
-		pkg_failed=yes
-	fi
 else
 	pkg_failed=untried
 fi
+if test -n "$PKG_CONFIG"; then
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\"gtk+-2.0 gdk-pixbuf-2.0\"\"") >&5
+  ($PKG_CONFIG --exists --print-errors ""gtk+-2.0 gdk-pixbuf-2.0"") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTK_LIBS=`$PKG_CONFIG --libs ""gtk+-2.0 gdk-pixbuf-2.0"" 2>/dev/null`
+else
+  pkg_failed=yes
 fi
-echo "$as_me:$LINENO: result: $pkg_cv_GTK_LIBS" >&5
-echo "${ECHO_T}$pkg_cv_GTK_LIBS" >&6
+else
+	pkg_failed=untried
+fi
 
 if test $pkg_failed = yes; then
 	GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors ""gtk+-2.0 gdk-pixbuf-2.0""`
@@ -20534,6 +20532,8 @@ elif test $pkg_failed = untried; then
 else
 	GTK_CFLAGS=$pkg_cv_GTK_CFLAGS
 	GTK_LIBS=$pkg_cv_GTK_LIBS
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 	have_gtk=yes
 
 cat >>confdefs.h <<\_ACEOF
